# Generated by Django 3.1.2 on 2020-10-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=250)),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('accuracy', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DrawTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column1', models.CharField(max_length=250)),
                ('column2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=250)),
                ('user', models.CharField(max_length=250)),
                ('accuracy', models.FloatField()),
            ],
        ),
    ]
