# Generated by Django 3.1.2 on 2020-10-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawtable',
            name='column2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
